### ISSUE TITLE
is-plain-object

### ISSUE THREAD

**Issue by doowb** [jonschlinkert/merge-deep#1]
Is there a reason for restricting this to plain objects?

**Comment by jonschlinkert** [comment]
it's used where [we're iterating over keys](https://github.com/jonschlinkert/merge-deep/blob/master/index.js#L28-L29) to copy the key-value pairs to the target. a plain object is one that's created by the `Object` constructor, so we'll know it has keys to iterate over. But [instance clones](https://github.com/jonschlinkert/clone-deep/blob/master/index.js#L35-L36) are done on other objects like arrays, date objects or regex

**Comment by doowb** [comment]
Oh... I see. I missed the parts using `clone-deep`.

**Comment by jonschlinkert** [comment]
no prob
