### ISSUE TITLE
doesn't browserify

### ISSUE THREAD

**Issue by TehShrike** [jonschlinkert/merge-deep#2]
The use of lazy-cache breaks browserify's ability to build this module.  Would you accept pull requests to drop lazy-cache from merge-deep and clone-deep?

**Comment by jonschlinkert** [comment]
this was using an old version of lazy-cache. would you mind pulling down the latest and trying again? (I just pushed up changes). As a last resort try using `process.env.UNLAZY = true`. But I don't think it will be needed with Browserify. For webpack, we have an unlazy-loader

**Comment by TehShrike** [comment]
Oh, brilliant.  I'll give this another try after the holidays and report back.

**Comment by jonschlinkert** [comment]
:+1: happy holidays!

**Comment by TehShrike** [comment]
It looks like shallow-copy relies on the old version of lazy-cache, as well as depending on a different version of kind-of than shallow-clone.

Also, lazy-cache referencing `process` means that browserify drops in a shim for the whole `process` object.

It looks like this module looks ends up with too many LOC to deploy to the browser - I'll just whip up my own small version I think.

Thanks for your time!
