### ISSUE TITLE
Misuse of CommonJS

### ISSUE THREAD

**Issue by TobiaszCudnik** [jonschlinkert/merge-deep#5]
From webpack:
```
WARNING in ./node_modules/merge-deep/utils.js
7:34-41 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/merge-deep/utils.js
 @ ./node_modules/merge-deep/index.js
```

**Comment by jonschlinkert** [comment]
You or webpack?

**Comment by fabio-b** [comment]
I'm getting this error too when bundling this library in with Webpack. Seems like ES6 import isn't supported with this library. Are there plans to have this library work with import statements?

`import merge from 'merge-deep'` gives the above error.

**Comment by doowb** [comment]
@fabio-b the correct syntax would be `import * as merge from 'merge-deep'` since `merge-deep` doesn't export a method named `merge`.

@TobiaszCudnik use the [unlazy-loader](https://github.com/doowb/unlazy-loader) in your webpack config if you're getting that error.
